name: build ble5 controller on push
run-name: ${{ github.actor }} is attempting to build ble5 controller on push to respository
on: 
  push:
    paths:
      - '/home/runner/work/stacks/stacks/controller/build/ble5-ctr/**'
      - '/home/runner/work/stacks/stacks/controller/build/common/**'
      - '/home/runner/work/stacks/stacks/controller/include/**'
      - '/home/runner/work/stacks/stacks/controller/sources/**'
jobs:
  build_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Update APT
        run: sudo apt-get update
      - name: Install ARM GNU Toolchain
        run: sudo apt-get install build-essential binutils-arm-none-eabi gcc-arm-none-eabi
      - name: Check where the ARM GNU Toolchain was installed
        run: |
          dpkg -L binutils-arm-none-eabi
          dpkg -L gcc-arm-none-eabi
      - name: Sync Repository Code
        uses: actions/checkout@v3
      - name: Dump root directory
        run: ls -all 
      - name: Build BLE5 Controller
        run: |
          export PATH=/usr/lib/gcc-arm-none-eabi/bin:/usr/lib/arm-none-eabi/bin:$PATH
          make -C controller/build/ble5-ctr/gcc
      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ble5-ctr.elf
          path: /home/runner/work/stacks/stacks/controller/build/ble5-ctr/gcc/bin/ble5-ctr.elf
          retention-days: 5
