name: build specific apps
run-name: ${{ github.actor }} is attempting to build specific apps on push to respository
on: [push]
jobs:
  setup_build_env:
    uses: ./.github/workflows/setup_build_env.yml
  sync_repository:
    name: Sync Repository
    needs: setup_build_env
    runs-on: ubuntu-latest
    steps:
      - name: Sync Repository Code
        uses: actions/checkout@v3
      - name: Dump root directory
        run: ls -all 
  build_app:
    needs: setup_runner
    uses: ./.github/workflows/build_app_on_call.yml
    with:
      folder: controller
      app: ble5-ctr
