name: build ble app asset tag on push
run-name: ${{ github.actor }} is attempting to build ble app asset tag on push to respository
on:
  push:
    paths:
      - '/home/runner/work/stacks/stacks/ble-apps/build/assettag/**'
      - '/home/runner/work/stacks/stacks/ble-apps/build/common/**'
      - '/home/runner/work/stacks/stacks/ble-apps/source/assettag/**'
      - '/home/runner/work/stacks/stacks/platform/**'
jobs:
  setup_build_env:
    uses: ./.github/workflows/setup_build_env.yml
  sync_repository:
    name: Sync Repository
    needs: setup_build_env
    runs-on: ubuntu-latest
    steps:
      - name: Sync Repository Code
        uses: actions/checkout@v3
      - name: Dump root directory
        run: ls -all 
  build_on_push:
    name: Build on Push
    needs: sync_repository
    runs-on: ubuntu-latest
    steps:
      - name: Build BLE APP Asset Tag
        run: |
          export PATH=/usr/lib/gcc-arm-none-eabi/bin:/usr/lib/arm-none-eabi/bin:$PATH
          make -C ble-apps/build/assettag/gcc
      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ble-apps-assettag.elf
          path: /home/runner/work/stacks/stacks/ble-apps/build/assettag/gcc/bin/assettag.elf
          retention-days: 5
